### ISSUE TITLE
Missing LICENSE

### ISSUE THREAD

**Issue by TechnologyClassroom** [librerpi/lk-overlay#1]
I see you have no LICENSE file for this project. The default is copyright.

I would suggest releasing the code under the GPL-2.0-or-later or GPL-3.0-or-later license so that others are encouraged to contribute changes back to your project.

**Comment by Vitali64** [comment]
Hello! We're working on it.

I'm currently thinking of using GPLv2-or-later.

~vitali64

**Comment by TechnologyClassroom** [comment]
I would suggest GPLv3-or-later unless you plan to submit patches to the Linux kernel.

**Comment by Vitali64** [comment]
OK, fixed, we licensed it under the GPLv2
because some code has been taken from 
Linux.

I can now close this(if I know how to do that).
