### ISSUE TITLE
[TODO] Move away from GitHub

### ISSUE THREAD

**Issue by funderscore1** [librerpi/lk-overlay#3]
Hello!
We're here to announce that we have plans to move away from GitHub to Notabug.org.

**Why are we doing this?**

GitHub is non-libre git hosting owned by Microsoft. 
We don't want to force people to use a non-libre tool just to send issues or pull requests.

**What will change with the GitHub repos?**

GitHub repos won't be deleted, they're gonna be used as mirrors.
Pull Requests and issues will still be accepted however. We'll still encourage to use Notabug.org 
for those tasks.

**What is Notabug.org?**

Notabug.org is the Peers Community's instance of their [modified version](https://notabug.org/hp/gogs/) of [Gogs](https://gogs.io/). Gogs is libre software, unlike GitHub.
It works similarily like GitHub and looks like GitHub.

**...**

If you have questions about that, feel free to ask them and we'll happily respond to them.

Have a nice day!

~vitali64

**Comment by MagicRB** [comment]
Why not sourcehut? Or freedesktop gitlab for that matter

**Comment by Vitali64** [comment]
Freedesktop GitLab requires way too much JavaScript and GitLab is only partially libre.
We also won't use SourceHut because it doesn't work like GitHub and might be 
confusing for other people (SourceHut is fine for me though).

**Comment by MagicRB** [comment]
Gitea? That works like a charm

**Comment by Vitali64** [comment]
Actually, we're also thinking about self-hosting Gitea ourselves instead of depending on someone else's Git service which may go down at any moment.
I unfortunately can't edit this issue! lol

**Comment by MagicRB** [comment]
Id offer my instance but I quite frequently forget to renew a certificate which causes downtime. Otherwise it's always up 😂

**Comment by bam80** [comment]
Where it was moved?
